### ISSUE TITLE
Matrix5x7 with 18 pins behind

### ISSUE THREAD

**Issue by rafantoninho** [felias-fogg/DotMatrix5x7#1]
Hello felias, i'ms from Brazil, and i need to make a display with a matrix 5x7, but there are 18 pins behind the matrix led.

Is there any difference between what you made?

This is the matrix, but there are 9 pins at top of the matriz led and 9 pins at the bottom.

![matriz_led_5x7_perfil_M](https://user-images.githubusercontent.com/79673147/136257528-5b30dd92-490a-4c0b-885c-a05376e4383c.jpg)

**Comment by felias-fogg** [comment]
Hi,

googling for LMD20057BSR-20 led me to the datasheet you find under https://datasheetspdf.com/pdf-file/901090/WENRUN/LMD20057BSR-20/1 .

From that, it seems that the display has 14 pins, where 5 and 12 as well as 3 and 11 are connected. 

In any case, when unsure, which pin is which, use a 5 volt source and a series resistor of 1 kΩ. Then try out all combinations of pins and write down at which point a LED lights up. From that you should be able to determine which pin is a row and which is a column pin, and which row resp. column it drives.
